version: '3'
 
services:

  zoo:
    image: confluentinc/cp-zookeeper:3.3.0
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: 10.123.11.177:22888:23888;10.123.11.178:22888:23888;10.123.11.179:22888:23888
    network_mode: host
    volumes:
      - "/mount/xvdb1/zk-data:/var/lib/zookeeper/data"
      - "/mount/xvdb1/zk-txn-logs:/var/lib/zookeeper/log"

  kafka:
    image: joncatlin/kafka-wait
    network_mode: host
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 10.123.11.177:22181,10.123.11.178:22181,10.123.11.179:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.123.11.178:29092
    volumes:
      - "/mount/xvdb1/kafka-logs:/var/lib/kafka/data"
  
  cb:
    image: couchbase
    network_mode: "host"
    volumes:
      - "/mount/xvdb1/jon_cb01:/opt/couchbase/var"
 
  statsd:
    image: hopsoft/graphite-statsd
    ports:
      - "8081:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    volumes:
      - /mount/xvdb1/graphite/:/opt/graphite
      - /mount/xvdb1/graphite-conf/:/opt/graphite/conf
      - /mount/xvdb1/graphite-storage/:/opt/graphite/storage
      - /mount/xvdb1/statsd/:/opt/statsd
 
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - /mount/xvdb1/grafana/:/var/lib/grafana
 
  kafka-consumer-accounts:
    image: joncatlin/kafka-consumer:1.0.5
    environment:
      - KAFKA_NODES=docker07.concordservicing.com:29092,docker08.concordservicing.com:29092,docker09.concordservicing.com:29092
      - COUCHBASE_NODES=docker07.concordservicing.com,docker08.concordservicing.com,docker09.concordservicing.com
      - KAFKA_TOPIC=AccountState
      - KAFKA_GROUP_ID=arch-group1
      - STATSD_SERVER=docker08.concordservicing.com
      - BATCH_SIZE=100

  kafka-consumer-portfolios:
    image: joncatlin/kafka-consumer:1.0.5
    environment:
      - KAFKA_NODES=docker07.concordservicing.com:29092,docker08.concordservicing.com:29092,docker09.concordservicing.com:29092
      - COUCHBASE_NODES=docker07.concordservicing.com,docker08.concordservicing.com,docker09.concordservicing.com
      - KAFKA_TOPIC=PortfolioState
      - KAFKA_GROUP_ID=arch-group2
      - STATSD_SERVER=docker08.concordservicing.com
      - BATCH_SIZE=100
